### ISSUE TITLE
Does S3Signer support IAM roles?

### ISSUE THREAD

**Issue by q42jaap** [kaliber-scala/play-s3#4]
Hey,

For my local test machine I'm using an IAM user with accessKey and SecretKey, but for on EC2 we're using IAM roles.
Does the S3 object or, the S3Signer support IAM roles?

**Comment by mellster2012** [comment]
For the example above, something along those lines (assuming play2 support): https://gist.github.com/mellster2012/b4eea2ba0f3d33126d0e
