### ISSUE TITLE
release to maven

### ISSUE THREAD

**Issue by graingert** [kaliber-scala/play-s3#67]

**Comment by EECOLOR** [comment]
Great suggestion, this however might take a while since releasing to sonatype is quite complicated.

**Comment by graingert** [comment]
@EECOLOR it's easy if you release via JCenter on Bintray first

**Comment by graingert** [comment]
@EECOLOR I've started the ball rolling: https://issues.sonatype.org/browse/OSSRH-22784

**Comment by jorkzijlstra** [comment]
Version 9.0.0 has been released to Maven
