### ISSUE TITLE
Direct upload sample from the README does not work

### ISSUE THREAD

**Issue by aleksandr-vin** [kaliber-scala/play-s3#73]
S3 reply:
```
<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>
Query-string authentication version 4 requires the X-Amz-Algorithm, X-Amz-Credential, X-Amz-Signature, X-Amz-Date, X-Amz-SignedHeaders, and X-Amz-Expires parameters.
</Message>
<RequestId>A5976FBEFEE951F2</RequestId>
<HostId>
xxxxxxxx</HostId>
</Error>
```

**Comment by aleksandr-vin** [comment]
You need to mention about the post method of the form

**Comment by EECOLOR** [comment]
@aleksandr-vin Could you propose the changes in https://github.com/kaliber-scala/play-s3/blob/master/README.md?

Click the 'edit' icon and add the documentation that would have prevented problems. Saving it will automatically create a pull request :smile:
