### ISSUE TITLE
Scala 2.12?

### ISSUE THREAD

**Issue by neilchaudhuri** [kaliber-scala/play-s3#74]
Is there any intention of creating a Scala 2.12 version of this library as Play 2.6 (with 2.12 support) is on the horizon?

Thanks.

**Comment by EECOLOR** [comment]
@neilchaudhuri I currently have quite a lot of work and thus not a lot of time for this open source library. I hope that one of the other members of the kaliber-scala organisation have more time.

You are however very welcome to create a pull request!

**Comment by Hayena** [comment]
@EECOLOR & @neilchaudhuri I've spend some time to update the library but was unable to fix all the changes done in Play 2.6. I will attempt to finish it up this weekend else I'll commit my progress so if anyone else has time they can round it up.
