### ISSUE TITLE
README.md should be updated 

### ISSUE THREAD

**Issue by navispeed** [kaliber-scala/play-s3#75]
In Readme, section Browser upload helpers:4

``` scala
 import fly.play.aws.policy.Condition.acl
```

Instead of 
``` scala
import fly.play.s3.upload.Condition._
```

Thanks.

**Comment by EECOLOR** [comment]
Thank you for reporting. You could easily create a pull request by clicking the `edit` button at https://github.com/kaliber-scala/play-s3/blob/master/README.md
