### ISSUE TITLE
Republish old versions?

### ISSUE THREAD

**Issue by EdgeCaseBerg** [kaliber-scala/play-s3#78]
Hi, we have an application that's using 5.0.2 of this library, and the other day after clearing my local ivy cache I got an error:

```
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: nl.rhinofly#play-s3_2.11;5.0.2: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
```

I [looked on maven central](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22play-s3_2.11%22) and saw that this version is not there anymore. Is there a different place where I can find the old releases? Or do I need to publish this locally in order to use the older version

FYI: My resolvers:
```
resolvers ++= Seq(
  "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/",
  "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
)
```

**Comment by EdgeCaseBerg** [comment]
I checked out the github release and published it locally and that worked, but while looking at the build file I noticed 

```
resolvers ++= Seq(
  "Rhinofly Internal Release Repository" at "http://maven-repository.rhinofly.net:8081/artifactory/libs-release-local",
  "Typesafe Release Repository" at "http://repo.typesafe.com/typesafe/releases")
  
```

and so I added `"Rhinofly Internal Release Repository" at "http://maven-repository.rhinofly.net:8081/artifactory/libs-release-local",` to my resolvers and things work fine now. Is this resolver going to keep around these old version or should I be replicating them somewhere I can rely on?

**Comment by EECOLOR** [comment]
Only last version was published on maven central. All the older versions were published in our (public) local repository. The url of the repository has changed the old url might go away. The new url will remain there for quite some time: https://jars.kaliber.io/artifactory/libs-release-local/

In other words, change it to the kaliber repo and you will be good.

**Comment by EdgeCaseBerg** [comment]
great, thank you very much!
