### ISSUE TITLE
Getting Error in installation, Unresolved Dependency

### ISSUE THREAD

**Issue by jsasj** [kaliber-scala/play-s3#82]
Hello,
I'm using Play 2.5.4
and scala version is 2.11.8
When I try to istall it I'm getting the following error
`sbt.ResolveException: unresolved dependency: net.kaliber#play-s3_2.11;8.0.1: not found`

**Comment by EECOLOR** [comment]
It seems there is a small error in the documentation. There is no version `8.0.1`, please try `8.0.0`

**Comment by jsasj** [comment]
That Worked for me, Thanks @EECOLOR
