### ISSUE TITLE
UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by jsasj** [kaliber-scala/play-s3#84]
`net.kaliber#play-s3_2.11;9.0.0: not found`
play-version:2.6
Scala version:2.11

**Comment by EECOLOR** [comment]
Yes, we are having trouble getting it to maven. It's in bintray: https://bintray.com/kaliber-scala/maven/play-s3/9.0.0

**Comment by EECOLOR** [comment]
https://dl.bintray.com/kaliber-scala/maven/

**Comment by jsasj** [comment]
I don't have Idea on how to add this to my dependency list in build.sbt. Could you please help.

**Comment by EECOLOR** [comment]
http://www.scala-sbt.org/0.13/docs/Resolvers.html

**Comment by jsasj** [comment]
Thanks, Job done

**Comment by EECOLOR** [comment]
Could you add the snippet you added here for others running into the same problem?

Once we have resolved the maven central issues you can remove the resolver.

**Comment by EECOLOR** [comment]
9.0.0 is on maven
