### ISSUE TITLE
RuntimeException: java.lang.NoClassDefFoundError: play/api/libs/ws/WSRequest$class

### ISSUE THREAD

**Issue by jsasj** [kaliber-scala/play-s3#85]
With Play version 2.6 and
Scala Version 2.11.8
I'm getting this error 
`RuntimeException: java.lang.NoClassDefFoundError: play/api/libs/ws/WSRequest$class`

**Comment by EECOLOR** [comment]
Wat version of play-s3 are you using?

**Comment by jsasj** [comment]
8.0.0

**Comment by lucianenache** [comment]
Version 8.0.0 is not compatible with play 2.6.x.

Either use play 2.5.x or use 9.0.0 of play-s3 (we are planning on releasing it to Maven these days)

**Comment by EECOLOR** [comment]
9.0.0 is on maven
