### ISSUE TITLE
jars.kaliber.io Down and/or very slow

### ISSUE THREAD

**Issue by hendorog** [kaliber-scala/play-s3#94]
Is it just me or is this repo down?

I get timeout errors in a clean build.

It's a shame as the module itself works great and has been really handy.

**Comment by EECOLOR** [comment]
What are you using as resolver url?

**Comment by Hayena** [comment]
I assume it's the one in the README `resolvers += "Kaliber Internal Repository" at "https://jars.kaliber.io/artifactory/libs-release-local"` since it also seems to be down for me

**Comment by bluedread** [comment]
Should be fixed now?

**Comment by hendorog** [comment]
Yes, looks good from here now. Thanks muchley.
